import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from "react";

type Language = "en" | "fr" | "ar";

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    login: "Login",
    register: "Register",
    logout: "Logout",
    profile: "Profile",
    messages: "Messages",
    dashboard: "Dashboard",
    favorites: "Favorites",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    settings: "Settings",
    findService: "Find a Service",
    joinProvider: "Join as Provider",
    heroTitle1: "Find the",
    heroTitle2: "Perfect Pro",
    heroTitle3: "for Every Job",
    heroSubtitle: "From home repairs to beauty services, connect with trusted professionals in your city today.",
    installApp: "Install App",
    installIosTitle: "Install the app",
    installIosShare: "Tap the Share button in Safari",
    installIosAdd: "Choose \"Add to Home Screen\"",
    installIosConfirm: "Tap \"Add\" to install Khidmati",
    installAndroidMenu: "Open the browser menu (the three dots)",
    installAndroidAddStep: "Choose \"Add to Home screen\" or \"Install app\"",
    installAndroidConfirm: "Tap \"Install\" to add Khidmati",
    installNow: "Install now",
    gotIt: "Got it",
    whatServiceNeed: "What service do you need?",
    search: "Search",
    popular: "Popular:",
    serviceProviders: "Service Providers",
    viewAll: "View All",
    noProvidersYet: "No providers registered yet. Try the search page or register as a provider.",
    exploreCategories: "Explore Categories",
    exploreCategoriesDesc: "Everything you need, right at your fingertips.",
    verifiedPros: "Verified Pros",
    verifiedProsDesc: "Every professional is vetted and verified for your peace of mind and safety.",
    fastBooking: "Fast Booking",
    fastBookingDesc: "Connect and book services instantly. No more waiting for callbacks.",
    communityRated: "Community Rated",
    communityRatedDesc: "Read real reviews from neighbors to pick the best person for the job.",
    areYouPro: "Are you a Professional?",
    joinProDesc: "Join thousands of providers growing their business with Khidmati. Get access to more clients and manage your work easily.",
    joinAsProvider: "Join as Provider",
    homeRepair: "Home Repair",
    beautySpa: "Beauty & Spa",
    cleaning: "Cleaning",
    moving: "Moving",
    electrician: "Electrician",
    plumbing: "Plumbing",
    tutoring: "Tutoring",
    techSupport: "Tech Support",
    findServices: "Find Services",
    searchByName: "Search by name or keyword...",
    allCategories: "All Categories",
    allCities: "All Cities",
    city: "City",
    category: "Category",
    list: "List",
    map: "Map",
    noResults: "No results found",
    tryAdjusting: "Try adjusting your filters or search terms.",
    showingProfessionals: "Showing {count} professionals",
    typeMessage: "Type a message...",
    selectConversation: "Select a conversation",
    chooseFromSidebar: "Choose from the sidebar to start messaging",
    noConversations: "No conversations yet.",
    messagesAutoDelete: "Messages auto-delete after 7 days",
    delete: "Delete",
    messageDeleted: "Message deleted",
    failedToSend: "Failed to send message",
    failedToDelete: "Failed to delete",
    onlyImagesAllowed: "Only images are allowed",
    imageTooLarge: "Image must be under 5MB",
    agreedPrice: "Agreed Price",
    pendingClientAgreement: "Pending client agreement",
    agree: "Agree",
    disagree: "Disagree",
    agreedAwaitingCash: "Agreed, awaiting cash",
    cashReceived: "Cash Received",
    didNotReceiveCash: "Did not receive cash",
    awaitingClientConfirmation: "Awaiting client confirmation",
    confirmCashPaid: "Confirm Cash Paid",
    paymentCompleted: "Payment Completed",
    downloadPdf: "Download PDF",
    priceRejectedByClient: "Price Rejected by Client",
    createCashInvoice: "Create Cash Invoice",
    serviceDescription: "Service Description",
    serviceDescriptionPlaceholder: "e.g., Fixed water leak...",
    agreedPriceMAD: "Agreed Price (MAD)",
    cashInvoiceNote: "Note: This invoice is for cash payment only.",
    proSpecialist: "Pro Specialist",
    clientProfile: "Client Profile",
    viewPublicProfile: "View Public Profile",
    exploreServices: "Explore Available Services",
    book: "Book Now",
    contact: "Contact",
    reviews: "Reviews",
    yearsExp: "years experience",
    available: "Available",
    unavailable: "Unavailable",
    bio: "About",
    citiesServed: "Cities Served",
    portfolio: "Portfolio",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    rating: "Rating",
    comment: "Comment",
    noReviews: "No reviews yet",
    loginToReview: "Login to write a review",
    professional: "Professional",
    new: "New",
    noBio: "No bio available.",
    remote: "Remote",
    myFavorites: "My Favorites",
    noFavorites: "No favorites yet",
    noFavoritesDesc: "Start exploring and save your favorite providers!",
    browseProviders: "Browse Providers",
    loading: "Loading...",
    error: "Something went wrong",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    welcome: "Find the best professionals for your needs",
    pleaseLogin: "Please login to view this page.",
    myBookings: "My Bookings",
    all: "All",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    rejected: "Rejected",
    searchBookings: "Search bookings...",
    noBookings: "No bookings yet",
    noBookingsDesc: "You haven't made any bookings yet.",
    bookingDetails: "Booking Details",
    cancelBooking: "Cancel Booking",
    contactProvider: "Contact Provider",
    payNow: "Pay Now",
    paid: "Paid",
    unpaid: "Unpaid",
    date: "Date",
    price: "Price",
    description: "Description",
    paymentStatus: "Payment Status",
    provider: "Provider",
    gridView: "Grid",
    listView: "List",
    sortBy: "Sort by",
    dateAdded: "Date added",
    searchFavorites: "Search favorites...",
    bookingNotFound: "Booking not found",
    completePayment: "Complete Payment",
    adminPortal: "Admin Portal",
    authorizedPersonnelOnly: "Authorized personnel only.",
    username: "Username",
    password: "Password",
    authenticating: "Authenticating...",
    accessDashboard: "Access Dashboard",
    secureAdminEnv: "Khidmati Secure Admin Environment v1.0",
    usersManagement: "Users Management",
    manageUsersRoles: "Manage users, roles, and access.",
    searchUsers: "Search users...",
    allUsers: "All Users",
    clients: "Clients",
    activeProviders: "Active Providers",
    pendingProviders: "Pending Providers",
    usersTable: "Users table",
    id: "ID",
    user: "User",
    role: "Role",
    status: "Status",
    joined: "Joined",
    actions: "Actions",
    noUsersFound: "No users found matching your search.",
    banned: "Banned",
    active: "Active",
    pendingApproval: "Pending Approval",
    activated: "Activated",
    activateProvider: "Activate Provider",
    viewDetails: "View Details",
    banUser: "Ban User",
    unbanUser: "Unban User",
    deleteUser: "Delete User",
    activateAccount: "Activate Account",
    confirmDeletion: "Confirm Deletion",
    confirmDeletionDesc: "This will permanently delete the user and all their data. This action cannot be undone.",
    deletePermanently: "Delete Permanently",
    userDeleted: "User deleted",
    userDeletedDesc: "The user has been successfully deleted.",
    deleteAccount: "Delete Account",
    deleteAccountDanger: "Danger Zone",
    deleteAccountCardDesc: "Once you delete your account, there is no going back. This will permanently remove your profile, bookings, messages, reviews and all associated data.",
    deleteAccountModalTitle: "Delete your account",
    deleteAccountModalSub: "We're sorry to see you go. Please review what will be deleted carefully.",
    deleteAccountWhatLoses: "What will be deleted:",
    deleteAccountData: "Your profile and personal data",
    deleteAccountBookings: "Your bookings and history",
    deleteAccountMessages: "Your messages and conversations",
    deleteAccountInvoices: "Your invoices",
    deleteAccountReviews: "Your reviews and ratings",
    deleteAccountFavorites: "Your saved favorites",
    deleteAccountReasonTitle: "Why are you leaving?",
    deleteAccountReasonSub: "Your feedback helps us improve Khidmati.",
    deleteReasonNotUseful: "No longer useful for me",
    deleteReasonAlternative: "I found another service",
    deleteReasonPrivacy: "Privacy concerns",
    deleteReasonNotifications: "Too many notifications",
    deleteReasonOther: "Other",
    deleteAccountConfirmTitle: "Final confirmation",
    deleteAccountConfirmDesc: "To delete your account permanently, type the phrase shown above and confirm below.",
    deleteAccountTypePhrase: "Type this phrase to delete your account",
    deleteAccountTypePlaceholder: "Type the highlighted phrase",
    deleteAccountUnderstand: "I understand that my account and all my data will be permanently deleted.",
    deleteAccountAction: "Delete my account permanently",
    deleteAccountSuccessTitle: "Account deleted",
    deleteAccountSuccessDesc: "Your account has been permanently deleted. We're sorry to see you go.",
    deleteAccountBackHome: "Back to home",
    continueBtn: "Continue",
    adminDeleteReason: "Deletion reason (shown to the user)",
    adminDeleteReasonPlaceholder: "Why is this account being deleted? The user will see this reason when trying to sign in.",
    adminDeleteReasonHint: "Max 500 characters. This will be displayed to the user at login.",
    adminDeleteReasonRequired: "A reason is required to delete the account",
    statusUpdated: "Status updated",
    statusUpdatedDesc: "User ban status has been updated.",
    providerActivated: "Provider activated",
    providerActivatedDesc: "The provider has been successfully activated.",
    operationFailed: "Operation failed",
    supportTickets: "Support Tickets",
    manageResolve: "Manage and resolve user issues.",
    allStatus: "All Status",
    open: "Open",
    resolved: "Resolved",
    closed: "Closed",
    priority: "Priority",
    allPriority: "All Priority",
    high: "High",
    normal: "Normal",
    low: "Low",
    searchTickets: "Search tickets...",
    ticketsTable: "Support tickets",
    subject: "Subject",
    created: "Created",
    action: "Action",
    noTicketsFound: "No tickets found.",
    viewTicket: "View Ticket",
    systemConfiguration: "System configuration and environment info.",
    adminAccount: "Admin Account",
    currentCredentials: "Current admin credentials configuration",
    configured: "Configured",
    notConfigured: "Not configured",
    environment: "Environment",
    serverRuntime: "Server runtime information",
    nodeEnvironment: "Node Environment",
    apiVersion: "API Version",
    integrations: "Integrations",
    thirdPartyStatus: "Third-party service status",
    googleOAuth: "Google OAuth",
    webPushVAPID: "Web Push (VAPID)",
    broadcastNotifications: "Broadcast notifications to all users",
    sendAnnouncements: "Send system-wide announcements from the Dashboard overview page.",
    setInEnv: "set in .env",
    reports: "Reports",
    downloadReports: "Download platform reports in CSV, Excel, or PDF format.",
    usersReport: "Users Report",
    usersReportDesc: "Export all users with roles, contact info, and status.",
    bookingsReport: "Bookings Report",
    bookingsReportDesc: "Export all bookings with dates, prices, and client/provider details.",
    ticketsReport: "Tickets Report",
    ticketsReportDesc: "Export all support tickets with status, priority, and user info.",
    summaryReport: "Summary Report",
    summaryReportDesc: "Export platform statistics: user counts, revenue, ticket summaries.",
    csv: "CSV",
    excel: "Excel",
    pdf: "PDF",
    aboutReports: "About Reports",
    csvDesc: "Opens in Excel, Google Sheets, or any text editor. Best for data processing.",
    excelDesc: "Proper spreadsheet format with formatting. Best for analysis.",
    pdfDesc: "Print-ready document. Best for sharing and archiving.",
    allRightsReserved: "All rights reserved.",
    // Dashboard & Stats
    overview: "Overview",
    totalUsers: "Total Users",
    totalProviders: "Total Providers",
    totalBookings: "Total Bookings",
    verificationRequests: "Verification Requests",
    totalRevenue: "Total Revenue",
    activeBookings: "Active Bookings",
    latestUsers: "Latest Users",
    latestBookings: "Latest Bookings",
    noUsersYet: "No users yet",
    noBookingsYet: "No bookings yet",
    userManagement: "User Management",
    filterByStatus: "Filter by Status",
    underReview: "Under Review",
    bookingManagement: "Booking Management",
    filterByBookingStatus: "Filter by booking status",
    customer: "Customer",
    accept: "Accept",
    reject: "Reject",
    revenueOverview: "Revenue Overview",
    invoices: "Invoices",
    invoiceNumber: "Invoice",
    amount: "Amount",
    viewInvoice: "View Invoice",
    confirmBan: "Confirm Ban",
    banDescription: "Are you sure you want to ban this user? They will lose access to the platform.",
    confirmBanAction: "Ban User",
    // Profile
    editProfile: "Edit Profile",
    downloadReport: "Download Report",
    pushNotifications: "Push Notifications",
    enableNotifications: "Enable Notifications",
    enableNotificationsDesc: "Receive push notifications for new bookings and messages.",
    totalBookingsStat: "Total Bookings",
    pendingBookings: "Pending",
    completedBookings: "Completed",
    recentBookings: "Recent Bookings",
    noRecurringBookings: "No recurring bookings yet",
    pause: "Pause",
    resume: "Resume",
    noTickets: "No tickets",
    newReply: "New reply",
    unread: "Unread",
    ticketReplied: "Replied",
    favoriteProviders: "Favorite Providers",
    reviewsAndRatings: "Reviews & Ratings",
    professionalInfo: "Professional Info",
    experience: "Experience",
    years: "years",
    earnings: "Earnings",
    noLocationPinned: "No location pinned",
    contactInfo: "Contact Info",
    noContactInfo: "No contact info added.",
    noPortfolioImages: "No portfolio images yet.",
    profilePhoto: "Profile Photo",
    changePhoto: "Change Photo",
    basicInformation: "Basic Information",
    tellAboutExperience: "Tell clients about your experience...",
    yearsOfExperience: "Years of Experience",
    yourCity: "Your city",
    workingHours: "Working Hours",
    clickMapToPin: "Click on the map to pin your exact location. This helps clients find you.",
    addImage: "Add Image",
    saveChanges: "Save Changes",
    editName: "Edit name",
    failedToSaveName: "Failed to save name",
    loadingProfile: "Loading profile...",
    morocco: "Morocco",
    noBioAdded: "No bio added yet.",
    noReviewsYet: "No reviews",
    // Provider Dashboard
    accountUnderReview: "Your account is under review",
    contactAdminWhatsApp: "Please contact administration via WhatsApp to activate your account.",
    activateViaWhatsApp: "Activate via WhatsApp",
    yourPhone: "Your phone number:",
    checkAccountStatus: "Check account status",
    dashboardSubtitle: "Manage your bookings and grow your business",
    newBookingRequest: "New Booking Request",
    viewBooking: "View Booking",
    sendMessage: "Send Message",
    viewMessages: "View Messages",
    myStats: "My Stats",
    totalEarnings: "Total Earnings",
    thisMonth: "This month",
    lastBooking: "Last Booking",
    averageRating: "Average Rating",
    activeCities: "Active Cities",
    quickActions: "Quick Actions",
    viewAllBookings: "View All Bookings",
    manageSchedule: "Manage Schedule",
    managePortfolio: "Manage Portfolio",
    recentMessages: "Recent Messages",
    noMessages: "No messages",
    bookingRequests: "Booking Requests",
    noBookingRequests: "No booking requests",
    noActiveCities: "No active cities",
    // Provider Reports
    providerReports: "My Reports",
    providerReportsDesc: "Download your personal reports.",
    myEarningsReport: "My Earnings",
    myEarningsDesc: "Export your earnings history with dates and amounts.",
    myBookingsReport: "My Bookings",
    myBookingsDesc: "Export all your bookings with dates, prices, and client details.",
    myReviewsReport: "My Reviews",
    myReviewsDesc: "Export all reviews received with ratings and comments.",
    performanceReport: "Performance Summary",
    performanceDesc: "Export your performance metrics: bookings completed, ratings, revenue.",
    // Invoices
    myInvoices: "My Invoices",
    searchInvoices: "Search (client, service, invoice #)...",
    noInvoices: "No invoices",
    noInvoicesDesc: "No completed invoices found.",
    noInvoicesDescFull: "You haven't issued or received any completed and confirmed invoices yet.",
    client: "Client",
    totalAmount: "Total Amount",
    view: "View",
    completedPaid: "Completed (Paid)",
    agreed: "Agreed",
    pendingAgreement: "Pending Agreement",
    awaitingPayment: "Awaiting Payment",
    invoice: "Invoice",
    // Invoice Print
    invoiceNotFound: "Invoice not found",
    invoiceNotReady: "This invoice is under review or incomplete and cannot be printed.",
    invoiceMustBeCompleted: "The invoice status must be 'Completed' to generate and download it as a receipt.",
    downloadPDF: "Download PDF",
    print: "Print",
    platformSlogan: "The leading platform for trusted home and professional services.",
    invoiceNumberLabel: "Invoice Number",
    dateLabel: "Date:",
    providerLabel: "Provider",
    billedTo: "Billed To",
    descriptionLabel: "Description",
    amountLabel: "Amount",
    paidLabel: "Paid",
    invoiceNote: "This invoice serves as a receipt for the agreed amount and payment has been confirmed by both parties.",
    subtotal: "Subtotal:",
    tax: "Tax (0%):",
    total: "Total:",
    thankYou: "Thank you for choosing our services",
    generatedBy: "Generated securely by Khidmati Platform",
    // Ticket Detail
    ticketNotFound: "Ticket not found",
    loadingTicket: "Loading ticket...",
    ticketStatusUpdated: "Ticket status updated",
    by: "By",
    closeTicket: "Close Ticket",
    markResolved: "Mark as Resolved",
    noRepliesYet: "No replies yet...",
    you: "You",
    admin: "Admin",
    ticketClosed: "This ticket is closed. You can no longer reply.",
    typeReply: "Type your reply...",
    // Support
    newTicket: "New Ticket",
    // Not Found
    pageNotFound: "Page Not Found",
    pageNotFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    goHome: "Go Home",
    searchServices: "Search Services",
    // Forgot/Reset Password
    forgotPassword: "Forgot Password",
    sendResetLink: "Send Reset Link",
    resetPassword: "Reset Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordResetSuccess: "Password Reset Successful",
    // Pending Provider
    accountUnderReviewShort: "Your account is under review",
    pendingReviewDesc: "Your account is under review. Please contact administration via WhatsApp.",
    contactAdmin: "Contact Admin via WhatsApp",
    phoneNumber: "Your phone number:",
    // Verification
    accountVerification: "Account Verification",
    verificationStatus: "Status:",
    verificationNotes: "Notes:",
    notVerified: "Not Verified",
    pendingReview: "Pending Review",
    verified: "Verified",
    rejectedVerification: "Rejected",
    submitVerification: "Submit Verification",
    verificationPending: "Your verification request is being reviewed. We'll notify you once it's approved.",
    verificationApproved: "Congratulations! Your account has been verified.",
    // Provider Verification specific
    submitVerificationRequest: "Submit Verification Request",
    documentType: "Document Type",
    documentNumber: "Document Number",
    documentPhoto: "Document Photo",
    uploadDocument: "Upload Document",
    idCard: "ID Card",
    passport: "Passport",
    businessLicense: "Business License",
    // Booking History extras
    bookingNumber: "Booking #",
    clientName: "Client",
    message: "Message",
    invoiceBtn: "Invoice",
    viewProfile: "Profile",
    quickStats: "Quick Stats",
    // Recurring
    recurringBookings: "Recurring Bookings",
    frequency: "Frequency",
    weekly: "Weekly",
    biweekly: "Bi-weekly",
    monthly: "Monthly",
    nextDate: "Next Date",
    // Common
    searchPlaceholder: "Search...",
    today: "Today",
    yesterday: "Yesterday",
    resetFilters: "Reset Filters",
    pro: "Pro",
    contactDetails: "Contact Details",
    enableNotificationsBtn: "Enable Notifications",
    searchConversations: "Search conversations...",
    cashInvoice: "Cash Invoice",
    createInvoice: "Create Invoice",
    sendInvoice: "Send Invoice",
    invoiceAmount: "Amount",
    invoiceNotes: "Notes",
    // Admin specific
    overviewTab: "Overview",
    usersTab: "Users",
    bookingsTab: "Bookings",
    verificationTab: "Verifications",
    revenueTab: "Revenue",
    invoicesTab: "Invoices",
    updateSuccess: "Updated",
    updateSuccessDesc: "User updated successfully",
    updateFailed: "Error",
    updateFailedDesc: "Failed to update user",
    verificationUpdated: "Verification updated",
    verificationFailed: "Failed to update verification",
    totalUsersLabel: "Total Users",
    providersLabel: "Providers",
    totalBookingsLabel: "Total Bookings",
    verificationLabel: "Verifications",
    revenueLabel: "Revenue",
    activeBookingsLabel: "Active Bookings",
    overviewLabel: "Overview",
    noUsersMessage: "No users yet",
    noBookingsMessage: "No bookings yet",
    usersManagementLabel: "User Management",
    searchLabel: "Search...",
    roleLabel: "Role",
    statusLabel: "Status",
    allRoles: "All",
    clientRole: "Client",
    providerRole: "Provider",
    adminRole: "Admin",
    activeStatus: "Active",
    underReviewStatus: "Under Review",
    rejectedStatus: "Rejected",
    name: "Name",
    usernameLabel: "Username",
    emailLabel: "Email",
    phoneLabel: "Phone",
    actionsLabel: "Actions",
    loadingLabel: "Loading...",
    noUsersFoundMessage: "No users found",
    adminRoleBadge: "Admin",
    providerRoleBadge: "Provider",
    clientRoleBadge: "Client",
    bookingManagementLabel: "Booking Management",
    filterByStatusLabel: "Filter by status",
    pendingStatus: "Pending",
    confirmedStatus: "Confirmed",
    completedStatus: "Completed",
    customerLabel: "Customer",
    professionalLabel: "Professional",
    acceptBtn: "Accept",
    rejectBtn: "Reject",
    acceptedLabel: "Accepted",
    rejectedLabel: "Rejected",
    revenueLabel2: "Revenue",
    totalLabel: "Total:",
    invoicesLabel: "Invoices",
    invoiceNumberLabel2: "Invoice #",
    clientProviderLabel: "Client/Provider",
    amountLabel2: "Amount",
    viewInvoiceBtn: "View Invoice",
    banConfirmTitle: "Confirm Ban",
    banConfirmDesc: "Are you sure you want to ban this user?",
    cancelBtn: "Cancel",
    confirmBanBtn: "Ban",
    // Provider specific booking labels
    activeStatusShort: "Active",
    confirmedStatusShort: "Confirmed",
    completedStatusShort: "Completed",
    cancelledStatusShort: "Cancelled",
    pendingStatusShort: "Pending",
    agreedStatusShort: "Agreed",
    // Notification extras
    allMarkedAsRead: "All marked as read",
    unreadCount: "{count} unread",
    allCaughtUp: "All caught up",
    markAllRead: "Mark all read",
    noNotificationsMessage: "No notifications",
    // Common extras
    confirmAction: "Confirm",
    confirmInChat: "Confirm in chat",
    statusUpdatedMessage: "Status updated",
    priceLabel: "Price",
    dateLabelShort: "Date",
    contactLabel: "Contact",
    viewAllLabel: "View All",
    messageLabel: "Message",
    cancelBtnLabel: "Cancel",
    payNowBtn: "Pay Now",
    invoiceBtnLabel: "Invoice",
    profileBtnLabel: "Profile",
    // Provider Dashboard stat cards
    monthlyEarnings: "Monthly Earnings",
    completedJobs: "Completed Jobs",
    pendingRequests: "Pending Requests",
    averageRatingLabel: "Average Rating",
    activeCitiesLabel: "Active Cities",
    heroBadge: "Morocco's #1 Home Services Platform",
    categories: "Categories",
    browseServices: "Browse Services",
    browseServicesDesc: "Choose from a wide range of home services",
    featured: "Featured",
    whyKhidmati: "Why Khidmati",
    platformTrust: "A platform you can trust",
    howItWorks: "How It Works",
    threeSteps: "3 Simple Steps",
    searchAService: "Search a Service",
    searchAServiceDesc: "Type the service you need and choose your city",
    chooseAPro: "Choose a Pro",
    chooseAProDesc: "Browse profiles, reviews and choose the best match",
    bookAndEnjoy: "Book & Enjoy",
    bookAndEnjoyDesc: "Book with one click and receive the pro at your convenience",
    forProfessionals: "For Professionals",
    freeSetup: "Free setup in 2 minutes",
    boostIncome: "Boost your income",
    thousandsClients: "Thousands of clients",
    proRating: "Pro Rating",
    adminDashboard: "Admin Dashboard",
    unnamedUser: "Unnamed User",
  },

  fr: {
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    profile: "Profil",
    messages: "Messages",
    dashboard: "Tableau de bord",
    favorites: "Favoris",
    notifications: "Notifications",
    noNotifications: "Aucune nouvelle notification",
    settings: "Paramètres",
    findService: "Trouver un Service",
    joinProvider: "Devenir Prestataire",
    heroTitle1: "Trouvez le",
    heroTitle2: "Pro Parfait",
    heroTitle3: "pour Chaque Travail",
    heroSubtitle: "Des réparations à domicile aux services de beauté, connectez-vous avec des professionnels de confiance dans votre ville.",
    installApp: "Installer l'App",
    installIosTitle: "Installer l'application",
    installIosShare: "Touchez le bouton Partager dans Safari",
    installIosAdd: "Choisissez \"Ajouter à l'écran d'accueil\"",
    installIosConfirm: "Touchez \"Ajouter\" pour installer Khidmati",
    installAndroidMenu: "Ouvrez le menu du navigateur (les trois points)",
    installAndroidAddStep: "Choisissez \"Ajouter à l'écran d'accueil\"",
    installAndroidConfirm: "Touchez \"Installer\" pour ajouter Khidmati",
    installNow: "Installer maintenant",
    gotIt: "Compris",
    whatServiceNeed: "De quel service avez-vous besoin ?",
    search: "Rechercher",
    popular: "Populaires :",
    serviceProviders: "Prestataires de Services",
    viewAll: "Voir Tout",
    noProvidersYet: "Aucun prestataire inscrit pour le moment. Essayez la page de recherche ou inscrivez-vous en tant que prestataire.",
    exploreCategories: "Explorer les Catégories",
    exploreCategoriesDesc: "Tout ce dont vous avez besoin, à portée de main.",
    verifiedPros: "Pros Vérifiés",
    verifiedProsDesc: "Chaque professionnel est vérifié pour votre tranquillité d'esprit et votre sécurité.",
    fastBooking: "Réservation Rapide",
    fastBookingDesc: "Connectez-vous et réservez instantanément. Plus besoin d'attendre.",
    communityRated: "Notés par la Communauté",
    communityRatedDesc: "Lisez les vrais avis de vos voisins pour choisir le meilleur professionnel.",
    areYouPro: "Êtes-vous un Professionnel ?",
    joinProDesc: "Rejoignez des milliers de prestataires qui développent leur activité avec Khidmati. Accédez à plus de clients et gérez votre travail facilement.",
    joinAsProvider: "Devenir Prestataire",
    homeRepair: "Réparation",
    beautySpa: "Beauté & Spa",
    cleaning: "Nettoyage",
    moving: "Déménagement",
    electrician: "Électricien",
    plumbing: "Plomberie",
    tutoring: "Tutorat",
    techSupport: "Support Tech",
    findServices: "Trouver des Services",
    searchByName: "Rechercher par nom ou mot-clé...",
    allCategories: "Toutes les Catégories",
    allCities: "Toutes les Villes",
    city: "Ville",
    category: "Catégorie",
    list: "Liste",
    map: "Carte",
    noResults: "Aucun résultat trouvé",
    tryAdjusting: "Essayez d'ajuster vos filtres ou termes de recherche.",
    showingProfessionals: "{count} professionnels trouvés",
    typeMessage: "Écrivez un message...",
    selectConversation: "Sélectionnez une conversation",
    chooseFromSidebar: "Choisissez dans la barre latérale pour commencer",
    noConversations: "Aucune conversation pour le moment.",
    messagesAutoDelete: "Les messages sont supprimés après 7 jours",
    delete: "Supprimer",
    messageDeleted: "Message supprimé",
    failedToSend: "Échec de l'envoi du message",
    failedToDelete: "Échec de la suppression",
    onlyImagesAllowed: "Seules les images sont autorisées",
    imageTooLarge: "L'image doit être inférieure à 5 Mo",
    agreedPrice: "Prix convenu",
    pendingClientAgreement: "En attente de l'accord du client",
    agree: "Accepter",
    disagree: "Refuser",
    agreedAwaitingCash: "Convenu, en attente du paiement",
    cashReceived: "Paiement reçu",
    didNotReceiveCash: "Paiement non reçu",
    awaitingClientConfirmation: "En attente de la confirmation du client",
    confirmCashPaid: "Confirmer le paiement",
    paymentCompleted: "Paiement complété",
    downloadPdf: "Télécharger le PDF",
    priceRejectedByClient: "Prix refusé par le client",
    createCashInvoice: "Créer une Facture Cash",
    serviceDescription: "Description du service",
    serviceDescriptionPlaceholder: "ex., Réparation fuite d'eau...",
    agreedPriceMAD: "Prix convenu (MAD)",
    cashInvoiceNote: "Note: Cette facture est pour le paiement en espèces uniquement.",
    proSpecialist: "Spécialiste Pro",
    clientProfile: "Profil Client",
    viewPublicProfile: "Voir le profil public",
    exploreServices: "Explorer les services disponibles",
    book: "Réserver",
    contact: "Contacter",
    reviews: "Avis",
    yearsExp: "ans d'expérience",
    available: "Disponible",
    unavailable: "Indisponible",
    bio: "À propos",
    citiesServed: "Villes desservies",
    portfolio: "Portfolio",
    writeReview: "Écrire un Avis",
    submitReview: "Soumettre l'Avis",
    rating: "Note",
    comment: "Commentaire",
    noReviews: "Aucun avis pour le moment",
    loginToReview: "Connectez-vous pour écrire un avis",
    professional: "Professionnel",
    new: "Nouveau",
    noBio: "Aucune bio disponible.",
    remote: "À distance",
    myFavorites: "Mes Favoris",
    noFavorites: "Aucun favori pour le moment",
    noFavoritesDesc: "Commencez à explorer et sauvegardez vos prestataires préférés !",
    browseProviders: "Parcourir les Prestataires",
    loading: "Chargement...",
    error: "Une erreur est survenue",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    back: "Retour",
    next: "Suivant",
    welcome: "Trouvez les meilleurs professionnels pour vos besoins",
    pleaseLogin: "Veuillez vous connecter pour voir cette page.",
    myBookings: "Mes Réservations",
    all: "Tous",
    pending: "En Attente",
    confirmed: "Confirmé",
    completed: "Terminé",
    rejected: "Rejeté",
    searchBookings: "Rechercher des réservations...",
    noBookings: "Aucune réservation",
    noBookingsDesc: "Vous n'avez encore fait aucune réservation.",
    bookingDetails: "Détails de la réservation",
    cancelBooking: "Annuler la réservation",
    contactProvider: "Contacter le prestataire",
    payNow: "Payer maintenant",
    paid: "Payé",
    unpaid: "Impayé",
    date: "Date",
    price: "Prix",
    description: "Description",
    paymentStatus: "Statut du paiement",
    provider: "Prestataire",
    gridView: "Grille",
    listView: "Liste",
    sortBy: "Trier par",
    dateAdded: "Date d'ajout",
    searchFavorites: "Rechercher dans les favoris...",
    bookingNotFound: "Réservation introuvable",
    completePayment: "Finaliser le paiement",
    adminPortal: "Portail Admin",
    authorizedPersonnelOnly: "Personnel autorisé uniquement.",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    authenticating: "Authentification...",
    accessDashboard: "Accéder au tableau de bord",
    secureAdminEnv: "Environnement Admin Sécurisé Khidmati v1.0",
    usersManagement: "Gestion des Utilisateurs",
    manageUsersRoles: "Gérer les utilisateurs, rôles et accès.",
    searchUsers: "Rechercher des utilisateurs...",
    allUsers: "Tous les Utilisateurs",
    clients: "Clients",
    activeProviders: "Prestataires Actifs",
    pendingProviders: "Prestataires en Attente",
    usersTable: "Table des utilisateurs",
    id: "ID",
    user: "Utilisateur",
    role: "Rôle",
    status: "Statut",
    joined: "Inscrit",
    actions: "Actions",
    noUsersFound: "Aucun utilisateur trouvé.",
    banned: "Banni",
    active: "Actif",
    pendingApproval: "En attente d'approbation",
    activated: "Activé",
    activateProvider: "Activer le prestataire",
    viewDetails: "Voir les détails",
    banUser: "Bloquer l'utilisateur",
    unbanUser: "Débloquer l'utilisateur",
    deleteUser: "Supprimer l'utilisateur",
    activateAccount: "Activer le compte",
    confirmDeletion: "Confirmer la suppression",
    confirmDeletionDesc: "Cela supprimera définitivement l'utilisateur et toutes ses données. Cette action est irréversible.",
    deletePermanently: "Supprimer définitivement",
    userDeleted: "Utilisateur supprimé",
    userDeletedDesc: "L'utilisateur a été supprimé avec succès.",
    deleteAccount: "Supprimer le compte",
    deleteAccountDanger: "Zone de danger",
    deleteAccountCardDesc: "Une fois votre compte supprimé, il n'y a pas de retour en arrière. Votre profil, vos réservations, messages, avis et toutes vos données seront définitivement supprimés.",
    deleteAccountModalTitle: "Supprimer votre compte",
    deleteAccountModalSub: "Nous sommes désolés de vous voir partir. Veuillez vérifier attentivement ce qui sera supprimé.",
    deleteAccountWhatLoses: "Ce qui sera supprimé :",
    deleteAccountData: "Votre profil et vos données personnelles",
    deleteAccountBookings: "Vos réservations et votre historique",
    deleteAccountMessages: "Vos messages et conversations",
    deleteAccountInvoices: "Vos factures",
    deleteAccountReviews: "Vos avis et évaluations",
    deleteAccountFavorites: "Vos favoris enregistrés",
    deleteAccountReasonTitle: "Pourquoi partez-vous ?",
    deleteAccountReasonSub: "Vos commentaires nous aident à améliorer Khidmati.",
    deleteReasonNotUseful: "Je n'en ai plus besoin",
    deleteReasonAlternative: "J'ai trouvé un autre service",
    deleteReasonPrivacy: "Problèmes de confidentialité",
    deleteReasonNotifications: "Trop de notifications",
    deleteReasonOther: "Autre",
    deleteAccountConfirmTitle: "Confirmation finale",
    deleteAccountConfirmDesc: "Pour supprimer votre compte définitivement, saisissez la phrase affichée ci-dessus et confirmez ci-dessous.",
    deleteAccountTypePhrase: "Saisissez cette phrase pour supprimer votre compte",
    deleteAccountTypePlaceholder: "Saisissez la phrase surlignée",
    deleteAccountUnderstand: "Je comprends que mon compte et toutes mes données seront définitivement supprimés.",
    deleteAccountAction: "Supprimer définitivement mon compte",
    deleteAccountSuccessTitle: "Compte supprimé",
    deleteAccountSuccessDesc: "Votre compte a été définitivement supprimé. Nous sommes désolés de vous voir partir.",
    deleteAccountBackHome: "Retour à l'accueil",
    continueBtn: "Continuer",
    adminDeleteReason: "Motif de suppression (visible par l'utilisateur)",
    adminDeleteReasonPlaceholder: "Pourquoi ce compte est-il supprimé ? L'utilisateur verra ce motif lors de la connexion.",
    adminDeleteReasonHint: "500 caractères maximum. Affiché à l'utilisateur à la connexion.",
    adminDeleteReasonRequired: "Un motif est requis pour supprimer le compte",
    statusUpdated: "Statut mis à jour",
    statusUpdatedDesc: "Le statut de blocage de l'utilisateur a été mis à jour.",
    providerActivated: "Prestataire activé",
    providerActivatedDesc: "Le prestataire a été activé avec succès.",
    operationFailed: "Échec de l'opération",
    supportTickets: "Tickets de Support",
    manageResolve: "Gérer et résoudre les problèmes utilisateurs.",
    allStatus: "Tous les statuts",
    open: "Ouvert",
    resolved: "Résolu",
    closed: "Fermé",
    priority: "Priorité",
    allPriority: "Toutes les priorités",
    high: "Haute",
    normal: "Normale",
    low: "Basse",
    searchTickets: "Rechercher des tickets...",
    ticketsTable: "Tickets de support",
    subject: "Sujet",
    created: "Créé",
    action: "Action",
    noTicketsFound: "Aucun ticket trouvé.",
    viewTicket: "Voir le ticket",
    systemConfiguration: "Configuration système et informations d'environnement.",
    adminAccount: "Compte Admin",
    currentCredentials: "Configuration des identifiants admin actuels",
    configured: "Configuré",
    notConfigured: "Non configuré",
    environment: "Environnement",
    serverRuntime: "Informations d'exécution du serveur",
    nodeEnvironment: "Environnement Node",
    apiVersion: "Version API",
    integrations: "Intégrations",
    thirdPartyStatus: "Statut des services tiers",
    googleOAuth: "Google OAuth",
    webPushVAPID: "Web Push (VAPID)",
    broadcastNotifications: "Diffuser des notifications à tous les utilisateurs",
    sendAnnouncements: "Envoyer des annonces système depuis l'aperçu du tableau de bord.",
    setInEnv: "défini dans .env",
    reports: "Rapports",
    downloadReports: "Télécharger les rapports de la plateforme en CSV, Excel ou PDF.",
    usersReport: "Rapport des Utilisateurs",
    usersReportDesc: "Exporter tous les utilisateurs avec rôles, contacts et statut.",
    bookingsReport: "Rapport des Réservations",
    bookingsReportDesc: "Exporter toutes les réservations avec dates, prix et détails client/prestataire.",
    ticketsReport: "Rapport des Tickets",
    ticketsReportDesc: "Exporter tous les tickets avec statut, priorité et infos utilisateur.",
    summaryReport: "Rapport Récapitulatif",
    summaryReportDesc: "Exporter les statistiques : nombre d'utilisateurs, revenus, résumés de tickets.",
    csv: "CSV",
    excel: "Excel",
    pdf: "PDF",
    aboutReports: "À propos des rapports",
    csvDesc: "S'ouvre dans Excel, Google Sheets ou éditeur de texte. Idéal pour le traitement de données.",
    excelDesc: "Format tableau avec mise en forme. Idéal pour l'analyse.",
    pdfDesc: "Document prêt à imprimer. Idéal pour le partage et l'archivage.",
    allRightsReserved: "Tous droits réservés.",
    overview: "Aperçu",
    totalUsers: "Total Utilisateurs",
    totalProviders: "Total Prestataires",
    totalBookings: "Total Réservations",
    verificationRequests: "Demandes de Vérification",
    totalRevenue: "Revenu Total",
    activeBookings: "Réservations Actives",
    latestUsers: "Derniers Utilisateurs",
    latestBookings: "Dernières Réservations",
    noUsersYet: "Aucun utilisateur",
    noBookingsYet: "Aucune réservation",
    userManagement: "Gestion des Utilisateurs",
    filterByStatus: "Filtrer par Statut",
    underReview: "En Revue",
    bookingManagement: "Gestion des Réservations",
    filterByBookingStatus: "Filtrer par statut",
    customer: "Client",
    accept: "Accepter",
    reject: "Rejeter",
    revenueOverview: "Aperçu des Revenus",
    invoices: "Factures",
    invoiceNumber: "Facture",
    amount: "Montant",
    viewInvoice: "Voir la Facture",
    confirmBan: "Confirmer le Blocage",
    banDescription: "Êtes-vous sûr de vouloir bloquer cet utilisateur ? Il perdra l'accès à la plateforme.",
    confirmBanAction: "Bloquer l'utilisateur",
    editProfile: "Modifier le Profil",
    downloadReport: "Télécharger le Rapport",
    pushNotifications: "Notifications Push",
    enableNotifications: "Activer les Notifications",
    enableNotificationsDesc: "Recevoir des notifications pour les nouvelles réservations et messages.",
    totalBookingsStat: "Total Réservations",
    pendingBookings: "En Attente",
    completedBookings: "Terminées",
    recentBookings: "Réservations Récentes",
    noRecurringBookings: "Aucune réservation récurrente",
    pause: "Pause",
    resume: "Reprendre",
    noTickets: "Aucun ticket",
    newReply: "Nouvelle réponse",
    unread: "Non lu",
    ticketReplied: "Répondu",
    favoriteProviders: "Prestataires Favoris",
    reviewsAndRatings: "Avis et Notes",
    professionalInfo: "Info Professionnelle",
    experience: "Expérience",
    years: "ans",
    earnings: "Gains",
    noLocationPinned: "Aucune position",
    contactInfo: "Info de Contact",
    noContactInfo: "Aucune info de contact.",
    noPortfolioImages: "Aucune image portfolio.",
    profilePhoto: "Photo de Profil",
    changePhoto: "Changer la Photo",
    basicInformation: "Informations de Base",
    tellAboutExperience: "Parlez de votre expérience...",
    yearsOfExperience: "Années d'Expérience",
    yourCity: "Votre ville",
    workingHours: "Horaires de Travail",
    clickMapToPin: "Cliquez sur la carte pour marker votre position précise.",
    addImage: "Ajouter une Image",
    saveChanges: "Enregistrer",
    editName: "Modifier le nom",
    failedToSaveName: "Échec de la sauvegarde",
    loadingProfile: "Chargement du profil...",
    morocco: "Maroc",
    noBioAdded: "Aucune bio ajoutée.",
    noReviewsYet: "Aucun avis",
    accountUnderReview: "Votre compte est en revue",
    contactAdminWhatsApp: "Veuillez contacter l'administration via WhatsApp pour activer votre compte.",
    activateViaWhatsApp: "Activer via WhatsApp",
    yourPhone: "Votre numéro :",
    checkAccountStatus: "Vérifier le statut",
    dashboardSubtitle: "Gérez vos réservations et développez votre activité",
    newBookingRequest: "Nouvelle Demande de Réservation",
    viewBooking: "Voir la Réservation",
    sendMessage: "Envoyer un Message",
    viewMessages: "Voir les Messages",
    myStats: "Mes Statistiques",
    totalEarnings: "Gains Totaux",
    thisMonth: "Ce mois",
    lastBooking: "Dernière Réservation",
    averageRating: "Note Moyenne",
    activeCities: "Villes Actives",
    quickActions: "Actions Rapides",
    viewAllBookings: "Voir Toutes les Réservations",
    manageSchedule: "Gérer l'Agenda",
    managePortfolio: "Gérer le Portfolio",
    recentMessages: "Messages Récents",
    noMessages: "Aucun message",
    bookingRequests: "Demandes de Réservation",
    noBookingRequests: "Aucune demande",
    noActiveCities: "Aucune ville active",
    providerReports: "Mes Rapports",
    providerReportsDesc: "Téléchargez vos rapports personnels.",
    myEarningsReport: "Mes Gains",
    myEarningsDesc: "Exporter l'historique de vos gains.",
    myBookingsReport: "Mes Réservations",
    myBookingsDesc: "Exporter toutes vos réservations.",
    myReviewsReport: "Mes Avis",
    myReviewsDesc: "Exporter tous les avis reçus.",
    performanceReport: "Résumé de Performance",
    performanceDesc: "Exporter vos métriques de performance.",
    myInvoices: "Mes Factures",
    searchInvoices: "Rechercher (client, service, #)...",
    noInvoices: "Aucune facture",
    noInvoicesDesc: "Aucune facture terminée trouvée.",
    noInvoicesDescFull: "Vous n'avez pas encore émis ou reçu de factures confirmées.",
    client: "Client",
    totalAmount: "Montant Total",
    view: "Voir",
    completedPaid: "Terminée (Payée)",
    agreed: "Convenue",
    pendingAgreement: "En Attente d'Accord",
    awaitingPayment: "En Attente de Paiement",
    invoice: "Facture",
    invoiceNotFound: "Facture introuvable",
    invoiceNotReady: "Cette facture est en revue ou incomplète.",
    invoiceMustBeCompleted: "Le statut doit être 'Terminée' pour générer le reçu.",
    downloadPDF: "Télécharger PDF",
    print: "Imprimer",
    platformSlogan: "La plateforme de référence pour les services de confiance.",
    invoiceNumberLabel: "Numéro de Facture",
    dateLabel: "Date :",
    providerLabel: "Prestataire",
    billedTo: "Facturé à",
    descriptionLabel: "Description",
    amountLabel: "Montant",
    paidLabel: "Payé",
    invoiceNote: "Cette facture sert de reçu pour le montant convenu.",
    subtotal: "Sous-total :",
    tax: "Taxe (0%) :",
    total: "Total :",
    thankYou: "Merci d'avoir choisi nos services",
    generatedBy: "Généré sécuritairement par Khidmati",
    ticketNotFound: "Ticket introuvable",
    loadingTicket: "Chargement du ticket...",
    ticketStatusUpdated: "Statut du ticket mis à jour",
    by: "Par",
    closeTicket: "Fermer le Ticket",
    markResolved: "Marquer comme Résolu",
    noRepliesYet: "Pas encore de réponses...",
    you: "Vous",
    admin: "Admin",
    ticketClosed: "Ce ticket est fermé. Vous ne pouvez plus répondre.",
    typeReply: "Écrivez votre réponse...",
    newTicket: "Nouveau Ticket",
    pageNotFound: "Page Non Trouvée",
    pageNotFoundDesc: "La page que vous cherchez n'existe pas ou a été déplacée.",
    goHome: "Accueil",
    searchServices: "Rechercher des Services",
    forgotPassword: "Mot de Passe Oublié",
    sendResetLink: "Envoyer le Lien",
    resetPassword: "Réinitialiser le Mot de Passe",
    newPassword: "Nouveau Mot de Passe",
    confirmPassword: "Confirmer le Mot de Passe",
    passwordResetSuccess: "Mot de Passe Réinitialisé",
    accountUnderReviewShort: "Votre compte est en revue",
    pendingReviewDesc: "Votre compte est en revue. Contactez l'administration via WhatsApp.",
    contactAdmin: "Contacter via WhatsApp",
    phoneNumber: "Votre numéro :",
    accountVerification: "Vérification du Compte",
    verificationStatus: "Statut :",
    verificationNotes: "Notes :",
    notVerified: "Non Vérifié",
    pendingReview: "En Revue",
    verified: "Vérifié",
    rejectedVerification: "Rejeté",
    submitVerification: "Soumettre la Vérification",
    verificationPending: "Votre demande est en cours de révision.",
    verificationApproved: "Félicitations ! Votre compte est vérifié.",
    submitVerificationRequest: "Soumettre la Demande",
    documentType: "Type de Document",
    documentNumber: "Numéro de Document",
    documentPhoto: "Photo du Document",
    uploadDocument: "Télécharger le Document",
    idCard: "Carte d'Identité",
    passport: "Passeport",
    businessLicense: "Licence Commerciale",
    bookingNumber: "Réservation #",
    clientName: "Client",
    message: "Message",
    invoiceBtn: "Facture",
    viewProfile: "Profil",
    quickStats: "Stats Rapides",
    recurringBookings: "Réservations Récurrentes",
    frequency: "Fréquence",
    weekly: "Hebdomadaire",
    biweekly: "Bimensuel",
    monthly: "Mensuel",
    nextDate: "Prochaine Date",
    searchPlaceholder: "Rechercher...",
    today: "Aujourd'hui",
    yesterday: "Hier",
    resetFilters: "Réinitialiser",
    pro: "Pro",
    contactDetails: "Détails de Contact",
    enableNotificationsBtn: "Activer les Notifications",
    searchConversations: "Rechercher...",
    cashInvoice: "Facture Cash",
    createInvoice: "Créer une Facture",
    sendInvoice: "Envoyer la Facture",
    invoiceAmount: "Montant",
    invoiceNotes: "Notes",
    overviewTab: "Aperçu",
    usersTab: "Utilisateurs",
    bookingsTab: "Réservations",
    verificationTab: "Vérifications",
    revenueTab: "Revenus",
    invoicesTab: "Factures",
    updateSuccess: "Mis à jour",
    updateSuccessDesc: "Utilisateur mis à jour avec succès",
    updateFailed: "Erreur",
    updateFailedDesc: "Échec de la mise à jour",
    verificationUpdated: "Vérification mise à jour",
    verificationFailed: "Échec de la vérification",
    totalUsersLabel: "Total Utilisateurs",
    providersLabel: "Prestataires",
    totalBookingsLabel: "Total Réservations",
    verificationLabel: "Vérifications",
    revenueLabel: "Revenus",
    activeBookingsLabel: "Réservations Actives",
    overviewLabel: "Aperçu",
    noUsersMessage: "Aucun utilisateur",
    noBookingsMessage: "Aucune réservation",
    usersManagementLabel: "Gestion des Utilisateurs",
    searchLabel: "Rechercher...",
    roleLabel: "Rôle",
    statusLabel: "Statut",
    allRoles: "Tous",
    clientRole: "Client",
    providerRole: "Prestataire",
    adminRole: "Admin",
    activeStatus: "Actif",
    underReviewStatus: "En Revue",
    rejectedStatus: "Rejeté",
    name: "Nom",
    usernameLabel: "Nom d'utilisateur",
    emailLabel: "Email",
    phoneLabel: "Téléphone",
    actionsLabel: "Actions",
    loadingLabel: "Chargement...",
    noUsersFoundMessage: "Aucun utilisateur trouvé",
    adminRoleBadge: "Admin",
    providerRoleBadge: "Prestataire",
    clientRoleBadge: "Client",
    bookingManagementLabel: "Gestion des Réservations",
    filterByStatusLabel: "Filtrer par statut",
    pendingStatus: "En Attente",
    confirmedStatus: "Confirmé",
    completedStatus: "Terminé",
    customerLabel: "Client",
    professionalLabel: "Professionnel",
    acceptBtn: "Accepter",
    rejectBtn: "Rejeter",
    acceptedLabel: "Accepté",
    rejectedLabel: "Rejeté",
    revenueLabel2: "Revenus",
    totalLabel: "Total :",
    invoicesLabel: "Factures",
    invoiceNumberLabel2: "Facture #",
    clientProviderLabel: "Client/Prestataire",
    amountLabel2: "Montant",
    viewInvoiceBtn: "Voir la Facture",
    banConfirmTitle: "Confirmer le Blocage",
    banConfirmDesc: "Êtes-vous sûr de vouloir bloquer cet utilisateur ?",
    cancelBtn: "Annuler",
    confirmBanBtn: "Bloquer",
    activeStatusShort: "Actif",
    confirmedStatusShort: "Confirmé",
    completedStatusShort: "Terminé",
    cancelledStatusShort: "Annulé",
    pendingStatusShort: "En Attente",
    agreedStatusShort: "Convenu",
    allMarkedAsRead: "Tout marqué comme lu",
    unreadCount: "{count} non lus",
    allCaughtUp: "Tout est à jour",
    markAllRead: "Tout marquer lu",
    noNotificationsMessage: "Aucune notification",
    confirmAction: "Confirmer",
    confirmInChat: "Confirmer dans le chat",
    statusUpdatedMessage: "Statut mis à jour",
    priceLabel: "Prix",
    dateLabelShort: "Date",
    contactLabel: "Contact",
    viewAllLabel: "Voir Tout",
    messageLabel: "Message",
    cancelBtnLabel: "Annuler",
    payNowBtn: "Payer",
    invoiceBtnLabel: "Facture",
    profileBtnLabel: "Profil",
    monthlyEarnings: "Gains Mensuels",
    completedJobs: "Jobs Terminés",
    pendingRequests: "Demandes en Attente",
    averageRatingLabel: "Note Moyenne",
    activeCitiesLabel: "Villes Actives",
    heroBadge: "La 1ère plateforme de services au Maroc",
    categories: "Catégories",
    browseServices: "Explorer les services",
    browseServicesDesc: "Choisissez parmi une large gamme de services",
    featured: "En vedette",
    whyKhidmati: "Pourquoi Khidmati",
    platformTrust: "Une plateforme de confiance",
    howItWorks: "Comment ça marche",
    threeSteps: "3 étapes simples",
    searchAService: "Rechercher un service",
    searchAServiceDesc: "Tapez le service dont vous avez besoin",
    chooseAPro: "Choisir un artisan",
    chooseAProDesc: "Parcourez les profils et choisissez le meilleur",
    bookAndEnjoy: "Réserver et profiter",
    bookAndEnjoyDesc: "Réservez en un clic et recevez l'artisan",
    forProfessionals: "Pour les artisans",
    freeSetup: "Configuration gratuite en 2 minutes",
    boostIncome: "Augmentez vos revenus",
    thousandsClients: "Des milliers de clients",
    proRating: "Note des artisans",
    adminDashboard: "Tableau de Bord Admin",
    unnamedUser: "Utilisateur sans nom",
  },

  ar: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "خروج",
    profile: "الملف الشخصي",
    messages: "الرسائل",
    dashboard: "لوحة التحكم",
    favorites: "المفضلة",
    notifications: "الإشعارات",
    noNotifications: "لا توجد إشعارات جديدة",
    settings: "الإعدادات",
    findService: "ابحث عن خدمة",
    joinProvider: "انضم كمقدم خدمة",
    heroTitle1: "اعثر على",
    heroTitle2: "المحترف المثالي",
    heroTitle3: "لكل مهمة",
    heroSubtitle: "من إصلاحات المنزل إلى خدمات التجميل، تواصل مع محترفين موثوقين في مدينتك اليوم.",
    installApp: "تحميل التطبيق",
    installIosTitle: "تثبيت التطبيق",
    installIosShare: "اضغط على زر المشاركة في سفاري",
    installIosAdd: "اختر \"إضافة إلى الشاشة الرئيسية\"",
    installIosConfirm: "اضغط على \"إضافة\" لتثبيت التطبيق",
    installAndroidMenu: "افتح قائمة المتصفح (النقاط الثلاث)",
    installAndroidAddStep: "اختر \"إضافة إلى الشاشة الرئيسية\" أو \"تثبيت التطبيق\"",
    installAndroidConfirm: "اضغط على \"تثبيت\" لإضافة التطبيق",
    installNow: "ثبّت الآن",
    gotIt: "حسناً",
    whatServiceNeed: "ما الخدمة التي تحتاجها؟",
    search: "بحث",
    popular: "الأكثر طلباً:",
    serviceProviders: "مزودو الخدمة",
    viewAll: "عرض الكل",
    noProvidersYet: "لا يوجد مزودون مسجلون حالياً. جرّب صفحة البحث أو سجّل كمزود خدمة.",
    exploreCategories: "استكشف الفئات",
    exploreCategoriesDesc: "كل ما تحتاجه في متناول يدك.",
    verifiedPros: "محترفون موثوقون",
    verifiedProsDesc: "كل محترف يتم التحقق منه لضمان راحتك وسلامتك.",
    fastBooking: "حجز سريع",
    fastBookingDesc: "تواصل واحجز خدماتك فوراً. لا مزيد من الانتظار.",
    communityRated: "تقييم المجتمع",
    communityRatedDesc: "اقرأ تقييمات حقيقية من جيرانك لاختيار أفضل محترف.",
    areYouPro: "هل أنت محترف؟",
    joinProDesc: "انضم لآلاف مقدمي الخدمات الذين ينمّون أعمالهم مع Khidmati. احصل على عملاء أكثر وأدر عملك بسهولة.",
    joinAsProvider: "انضم كمقدم خدمة",
    homeRepair: "إصلاح المنزل",
    beautySpa: "تجميل وسبا",
    cleaning: "تنظيف",
    moving: "نقل",
    electrician: "كهربائي",
    plumbing: "سباكة",
    tutoring: "دروس خصوصية",
    techSupport: "دعم تقني",
    findServices: "ابحث عن خدمات",
    searchByName: "ابحث بالاسم أو الكلمة...",
    allCategories: "جميع الفئات",
    allCities: "جميع المدن",
    city: "المدينة",
    category: "الفئة",
    list: "قائمة",
    map: "خريطة",
    noResults: "لا توجد نتائج",
    tryAdjusting: "حاول تعديل الفلاتر أو كلمات البحث.",
    showingProfessionals: "عرض {count} محترف",
    typeMessage: "اكتب رسالة...",
    selectConversation: "اختر محادثة",
    chooseFromSidebar: "اختر من القائمة الجانبية لبدء المراسلة",
    noConversations: "لا توجد محادثات بعد.",
    messagesAutoDelete: "تُحذف الرسائل تلقائياً بعد 7 أيام",
    delete: "حذف",
    messageDeleted: "تم حذف الرسالة",
    failedToSend: "فشل إرسال الرسالة",
    failedToDelete: "فشل الحذف",
    onlyImagesAllowed: "الصور فقط مسموح بها",
    imageTooLarge: "حجم الصورة يجب أن يكون أقل من 5 ميجا",
    agreedPrice: "السعر المتفق عليه",
    pendingClientAgreement: "بانتظار موافقة العميل",
    agree: "موافق على السعر",
    disagree: "غير موافق",
    agreedAwaitingCash: "تم الاتفاق، بانتظار استلام الكاش",
    cashReceived: "تم استلام المبلغ",
    didNotReceiveCash: "لم يتم استلام المبلغ",
    awaitingClientConfirmation: "بانتظار تأكيد العميل",
    confirmCashPaid: "تأكيد دفع المبلغ",
    paymentCompleted: "مكتملة الدفع",
    downloadPdf: "تحميل الفاتورة",
    priceRejectedByClient: "تم رفض السعر من قبل العميل",
    createCashInvoice: "إنشاء فاتورة دفع نقدي",
    serviceDescription: "وصف المشكلة / الخدمة",
    serviceDescriptionPlaceholder: "مثال: إصلاح تسرب المياه في المطبخ...",
    agreedPriceMAD: "السعر المتفق عليه (درهم)",
    cashInvoiceNote: "تنبيه: هذه الفاتورة للدفع النقدي يداً بيد. لا يتم الدفع عبر الإنترنت.",
    proSpecialist: "حرفي محترف",
    clientProfile: "عميل المنصة",
    viewPublicProfile: "عرض الملف الشخصي الكامل",
    exploreServices: "استكشاف الخدمات المتاحة",
    book: "احجز الآن",
    contact: "تواصل",
    reviews: "التقييمات",
    yearsExp: "سنوات خبرة",
    available: "متاح",
    unavailable: "غير متاح",
    bio: "نبذة",
    citiesServed: "المدن المخدومة",
    portfolio: "أعمال سابقة",
    writeReview: "اكتب تقييم",
    submitReview: "إرسال التقييم",
    rating: "التقييم",
    comment: "التعليق",
    noReviews: "لا توجد تقييمات بعد",
    loginToReview: "سجّل دخولك لكتابة تقييم",
    professional: "محترف",
    new: "جديد",
    noBio: "لا توجد نبذة.",
    remote: "عن بُعد",
    myFavorites: "المفضلة",
    noFavorites: "لا توجد مفضلات بعد",
    noFavoritesDesc: "ابدأ بالاستكشاف واحفظ مزودي الخدمة المفضلين لديك!",
    browseProviders: "تصفح المزودين",
    loading: "جاري التحميل...",
    error: "حدث خطأ ما",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    back: "رجوع",
    next: "التالي",
    welcome: "اعثر على أفضل المحترفين لاحتياجاتك",
    pleaseLogin: "يرجى تسجيل الدخول لعرض هذه الصفحة.",
    myBookings: "حجوزاتي",
    all: "الكل",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    completed: "مكتمل",
    rejected: "ملغي",
    searchBookings: "ابحث في الحجوزات...",
    noBookings: "لا توجد حجوزات",
    noBookingsDesc: "لم تقم بأي حجوزات بعد.",
    bookingDetails: "تفاصيل الحجز",
    cancelBooking: "إلغاء الحجز",
    contactProvider: "تواصل مع الحرفي",
    payNow: "ادفع الآن",
    paid: "مدفوع",
    unpaid: "غير مدفوع",
    date: "التاريخ",
    price: "السعر",
    description: "الوصف",
    paymentStatus: "حالة الدفع",
    provider: "الحرفي",
    gridView: "شبكي",
    listView: "قائمة",
    sortBy: "ترتيب حسب",
    dateAdded: "تاريخ الإضافة",
    searchFavorites: "ابحث في المفضلات...",
    bookingNotFound: "الحجز غير موجود",
    completePayment: "إتمام الدفع",
    adminPortal: "بوابة الإدارة",
    authorizedPersonnelOnly: "للكبار فحسب.",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    authenticating: "جاري المصادقة...",
    accessDashboard: "الدخول للوحة التحكم",
    secureAdminEnv: "بيئة الإدارة الآمنة Khidmati v1.0",
    usersManagement: "إدارة المستخدمين",
    manageUsersRoles: "إدارة المستخدمين والأدوار والصلاحيات.",
    searchUsers: "بحث في المستخدمين...",
    allUsers: "جميع المستخدمين",
    clients: "العملاء",
    activeProviders: "المزودون النشطون",
    pendingProviders: "المزودون بانتظار الموافقة",
    usersTable: "جدول المستخدمين",
    id: "المعرف",
    user: "المستخدم",
    role: "الدور",
    status: "الحالة",
    joined: "تاريخ الانضمام",
    actions: "الإجراءات",
    noUsersFound: "لا يوجد مستخدمون يطابقون بحثك.",
    banned: "محظور",
    active: "نشط",
    pendingApproval: "بانتظار الموافقة",
    activated: "مفعّل",
    activateProvider: "تفعيل المزود",
    viewDetails: "عرض التفاصيل",
    banUser: "حظر المستخدم",
    unbanUser: "إلغاء الحظر",
    deleteUser: "حذف المستخدم",
    activateAccount: "تفعيل الحساب",
    confirmDeletion: "تأكيد الحذف",
    confirmDeletionDesc: "سيتم حذف المستخدم وجميع بياناته نهائياً. هذا الإجراء لا يمكن التراجع عنه.",
    deletePermanently: "حذف نهائي",
    userDeleted: "تم حذف المستخدم",
    userDeletedDesc: "تم حذف المستخدم بنجاح.",
    deleteAccount: "حذف الحساب",
    deleteAccountDanger: "منطقة الخطر",
    deleteAccountCardDesc: "بمجرد حذف حسابك لن يكون هناك رجوع. سيتم حذف ملفك الشخصي وحجوزاتك ورسائلك وتقييماتك وكل البيانات المرتبطة نهائياً.",
    deleteAccountModalTitle: "حذف حسابك",
    deleteAccountModalSub: "نأسف لرؤيتك ترحل. يرجى مراجعة ما سيتم حذفه بعناية.",
    deleteAccountWhatLoses: "ما الذي سيتم حذفه؟",
    deleteAccountData: "ملفك الشخصي وبياناتك الشخصية",
    deleteAccountBookings: "حجوزاتك وسجلّك",
    deleteAccountMessages: "رسائلك ومحادثاتك",
    deleteAccountInvoices: "فواتيرك",
    deleteAccountReviews: "تقييماتك وملاحظاتك",
    deleteAccountFavorites: "المفضلة المحفوظة لديك",
    deleteAccountReasonTitle: "لماذا تغادر؟",
    deleteAccountReasonSub: "ملاحظاتك تساعدنا على تحسين Khidmati.",
    deleteReasonNotUseful: "لم تعد مفيدة لي",
    deleteReasonAlternative: "وجدت خدمة أخرى",
    deleteReasonPrivacy: "مخاوف الخصوصية",
    deleteReasonNotifications: "إشعارات كثيرة",
    deleteReasonOther: "أخرى",
    deleteAccountConfirmTitle: "التأكيد النهائي",
    deleteAccountConfirmDesc: "لحذف حسابك نهائياً، اكتب الجملة الظاهرة أعلاه ثم قم بالتأكيد أدناه.",
    deleteAccountTypePhrase: "اكتب هذه الجملة لحذف حسابك",
    deleteAccountTypePlaceholder: "اكتب الجملة المميزة",
    deleteAccountUnderstand: "أفهم أن حسابي وكل بياناتي سيتم حذفها نهائياً.",
    deleteAccountAction: "حذف حسابي نهائياً",
    deleteAccountSuccessTitle: "تم حذف الحساب",
    deleteAccountSuccessDesc: "تم حذف حسابك نهائياً. نأسف لرؤيتك ترحل.",
    deleteAccountBackHome: "العودة للرئيسية",
    continueBtn: "متابعة",
    adminDeleteReason: "سبب الحذف (سيظهر للمستخدم)",
    adminDeleteReasonPlaceholder: "لماذا يتم حذف هذا الحساب؟ سيرى المستخدم هذا السبب عند محاولة تسجيل الدخول.",
    adminDeleteReasonHint: "بحد أقصى 500 حرف. سيظهر للمستخدم عند تسجيل الدخول.",
    adminDeleteReasonRequired: "السبب مطلوب لحذف الحساب",
    statusUpdated: "تم تحديث الحالة",
    statusUpdatedDesc: "تم تحديث حالة الحظر.",
    providerActivated: "تم تفعيل المزود",
    providerActivatedDesc: "تم تفعيل المزود بنجاح.",
    operationFailed: "فشلت العملية",
    supportTickets: "تذاكر الدعم",
    manageResolve: "إدارة وحل مشاكل المستخدمين.",
    allStatus: "جميع الحالات",
    open: "مفتوح",
    resolved: "تم الحل",
    closed: "مغلق",
    priority: "الأولوية",
    allPriority: "جميع الأولويات",
    high: "عالية",
    normal: "عادية",
    low: "منخفضة",
    searchTickets: "بحث في التذاكر...",
    ticketsTable: "تذاكر الدعم",
    subject: "الموضوع",
    created: "تاريخ الإنشاء",
    action: "إجراء",
    noTicketsFound: "لا توجد تذاكر.",
    viewTicket: "عرض التذكرة",
    systemConfiguration: "معلومات الإعدادات والنظام.",
    adminAccount: "حساب المدير",
    currentCredentials: "إعدادات بيانات الدخول الحالية",
    configured: "مُعد",
    notConfigured: "غير مُعد",
    environment: "البيئة",
    serverRuntime: "معلومات تشغيل السيرفر",
    nodeEnvironment: "بيئة Node",
    apiVersion: "إصدار API",
    integrations: "التكاملات",
    thirdPartyStatus: "حالة الخدمات الخارجية",
    googleOAuth: "Google OAuth",
    webPushVAPID: "Web Push (VAPID)",
    broadcastNotifications: "إرسال إشعارات لجميع المستخدمين",
    sendAnnouncements: "إرسال إعلانات من صفحة لوحة التحكم.",
    setInEnv: "يُحدّد في .env",
    reports: "التقارير",
    downloadReports: "تحميل تقارير المنصة بصيغ CSV أو Excel أو PDF.",
    usersReport: "تقرير المستخدمين",
    usersReportDesc: "تصدير جميع المستخدمين مع الأدوار ومعلومات الاتصال والحالة.",
    bookingsReport: "تقرير الحجوزات",
    bookingsReportDesc: "تصدير جميع الحجوزات مع التواريخ والأسعار وتفاصيل العميل/المزود.",
    ticketsReport: "تقرير التذاكر",
    ticketsReportDesc: "تصدير جميع تذاكر الدعم مع الحالة والأولوية ومعلومات المستخدم.",
    summaryReport: "تقرير ملخص",
    summaryReportDesc: "تصدير إحصائيات المنصة: عدد المستخدمين، الإيرادات، ملخصات التذاكر.",
    csv: "CSV",
    excel: "Excel",
    pdf: "PDF",
    aboutReports: "عن التقارير",
    csvDesc: "يُفتح في Excel أو Google Sheets أو أي محرر نصوص. الأفضل لمعالجة البيانات.",
    excelDesc: "صيغة جداول بيانات مع تنسيق. الأفضل للتحليل.",
    pdfDesc: "مستند جاهز للطباعة. الأفضل للمشاركة والأرشيف.",
    allRightsReserved: "جميع الحقوق محفوظة.",
    overview: "نظرة عامة",
    totalUsers: "إجمالي المستخدمين",
    totalProviders: "إجمالي المزودين",
    totalBookings: "إجمالي الحجوزات",
    verificationRequests: "طلبات التوثيق",
    totalRevenue: "إجمالي الإيرادات",
    activeBookings: "الحجوزات النشطة",
    latestUsers: "آخر المستخدمين",
    latestBookings: "آخر الحجوزات",
    noUsersYet: "لا يوجد مستخدمين بعد",
    noBookingsYet: "لا توجد حجوزات بعد",
    userManagement: "إدارة المستخدمين",
    filterByStatus: "تصفية حسب الحالة",
    underReview: "قيد المراجعة",
    bookingManagement: "إدارة الحجوزات",
    filterByBookingStatus: "تصفية حسب حالة الحجز",
    customer: "عميل",
    accept: "قبول",
    reject: "رفض",
    revenueOverview: "نظرة على الإيرادات",
    invoices: "الفواتير",
    invoiceNumber: "فاتورة",
    amount: "المبلغ",
    viewInvoice: "عرض الفاتورة",
    confirmBan: "تأكيد الحظر",
    banDescription: "هل أنت متأكد من حظر هذا المستخدم؟ سيفقد الوصول للمنصة.",
    confirmBanAction: "حظر المستخدم",
    editProfile: "تعديل الملف الشخصي",
    downloadReport: "تحميل التقرير",
    pushNotifications: "الإشعارات الفورية",
    enableNotifications: "تفعيل الإشعارات",
    enableNotificationsDesc: "استقبال إشعارات للحجوزات والرسائل الجديدة.",
    totalBookingsStat: "إجمالي الحجوزات",
    pendingBookings: "قيد الانتظار",
    completedBookings: "مكتملة",
    recentBookings: "الحجوزات الأخيرة",
    noRecurringBookings: "لا توجد حجوزات دورية",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    noTickets: "لا توجد تذاكر",
    newReply: "رد جديد",
    unread: "غير مقروء",
    ticketReplied: "تم الرد",
    favoriteProviders: "المزودون المفضلون",
    reviewsAndRatings: "التقييمات والمراجعات",
    professionalInfo: "المعلومات المهنية",
    experience: "الخبرة",
    years: "سنوات",
    earnings: "الأرباح",
    noLocationPinned: "لم يتم تحديد الموقع",
    contactInfo: "معلومات الاتصال",
    noContactInfo: "لم تُضف معلومات اتصال.",
    noPortfolioImages: "لا توجد صور أعمال سابقة.",
    profilePhoto: "صورة الملف الشخصي",
    changePhoto: "تغيير الصورة",
    basicInformation: "المعلومات الأساسية",
    tellAboutExperience: "أخبر العملاء عن خبراتك...",
    yearsOfExperience: "سنوات الخبرة",
    yourCity: "مدينتك",
    workingHours: "ساعات العمل",
    clickMapToPin: "انقر على الخريطة لتحديد موقعك بالضبط.",
    addImage: "إضافة صورة",
    saveChanges: "حفظ التغييرات",
    editName: "تعديل الاسم",
    failedToSaveName: "فشل حفظ الاسم",
    loadingProfile: "جاري تحميل الملف...",
    morocco: "المغرب",
    noBioAdded: "لم تُضف نبذة بعد.",
    noReviewsYet: "لا توجد تقييمات",
    accountUnderReview: "حسابك قيد المراجعة",
    contactAdminWhatsApp: "يرجى التواصل مع الإدارة عبر واتساب لتفعيل حسابك.",
    activateViaWhatsApp: "تفعيل عبر واتساب",
    yourPhone: "رقم هاتفك:",
    checkAccountStatus: "التحقق من حالة الحساب",
    dashboardSubtitle: "أدر حجوزاتك ونمّي أعمالك",
    newBookingRequest: "طلب حجز جديد",
    viewBooking: "عرض الحجز",
    sendMessage: "إرسال رسالة",
    viewMessages: "عرض الرسائل",
    myStats: "إحصائياتي",
    totalEarnings: "إجمالي الأرباح",
    thisMonth: "هذا الشهر",
    lastBooking: "آخر حجز",
    averageRating: "متوسط التقييم",
    activeCities: "المدن النشطة",
    quickActions: "إجراءات سريعة",
    viewAllBookings: "عرض جميع الحجوزات",
    manageSchedule: "إدارة الجدول",
    managePortfolio: "إدارة الأعمال",
    recentMessages: "الرسائل الأخيرة",
    noMessages: "لا توجد رسائل",
    bookingRequests: "طلبات الحجز",
    noBookingRequests: "لا توجد طلبات حجز",
    noActiveCities: "لا توجد مدن نشطة",
    providerReports: "تقاريري",
    providerReportsDesc: "تحميل التقارير الشخصية.",
    myEarningsReport: "أرباحي",
    myEarningsDesc: "تصدير سجل الأرباح.",
    myBookingsReport: "حجوزاتي",
    myBookingsDesc: "تصدير جميع الحجوزات.",
    myReviewsReport: "تقييماتي",
    myReviewsDesc: "تصدير جميع التقييمات المستلمة.",
    performanceReport: "ملخص الأداء",
    performanceDesc: "تصدير مقاييس الأداء.",
    myInvoices: "فواتيري",
    searchInvoices: "بحث (عميل، خدمة، رقم فاتورة)...",
    noInvoices: "لا توجد فواتير",
    noInvoicesDesc: "لم يتم العثور على فواتير مكتملة.",
    noInvoicesDescFull: "لم تُصدر أو تستلم أي فواتير مكتملة ومؤكدة بعد.",
    client: "العميل",
    totalAmount: "المبلغ الإجمالي",
    view: "عرض",
    completedPaid: "مكتملة (مدفوعة)",
    agreed: "متفق عليها",
    pendingAgreement: "بانتظار الموافقة",
    awaitingPayment: "بانتظار تأكيد الدفع",
    invoice: "فاتورة",
    invoiceNotFound: "الفاتورة غير موجودة",
    invoiceNotReady: "هذه الفاتورة قيد المراجعة أو غير مكتملة.",
    invoiceMustBeCompleted: "يجب أن تكون حالة الفاتورة مكتملة لتوليدها.",
    downloadPDF: "تحميل PDF",
    print: "طباعة",
    platformSlogan: "المنصة الرائدة للخدمات المنزلية والمهنية الموثوقة.",
    invoiceNumberLabel: "رقم الفاتورة",
    dateLabel: "التاريخ:",
    providerLabel: "مقدم الخدمة",
    billedTo: "فاتورة إلى",
    descriptionLabel: "الوصف",
    amountLabel: "المبلغ",
    paidLabel: "مدفوع",
    invoiceNote: "هذه الفاتورة تعتبر إيصال استلام للمبلغ المتفق عليه.",
    subtotal: "المجموع الفرعي:",
    tax: "الضريبة (0%):",
    total: "الإجمالي:",
    thankYou: "نشكركم على اختيار خدماتنا",
    generatedBy: "تم التوليد بشكل آمن بواسطة منصة Khidmati",
    ticketNotFound: "التذكرة غير موجودة",
    loadingTicket: "جاري تحميل التذكرة...",
    ticketStatusUpdated: "تم تحديث حالة التذكرة",
    by: "بواسطة",
    closeTicket: "إغلاق التذكرة",
    markResolved: "تحديد كمحلولة",
    noRepliesYet: "لا توجد ردود بعد...",
    you: "أنت",
    admin: "المدير",
    ticketClosed: "هذه التذكرة مغلقة. لا يمكنك الرد.",
    typeReply: "اكتب ردك...",
    newTicket: "تذكرة جديدة",
    pageNotFound: "الصفحة غير موجودة",
    pageNotFoundDesc: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    goHome: "الرئيسية",
    searchServices: "البحث عن خدمات",
    forgotPassword: "نسيت كلمة المرور",
    sendResetLink: "إرسال رابط إعادة التعيين",
    resetPassword: "إعادة تعيين كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordResetSuccess: "تم إعادة تعيين كلمة المرور بنجاح",
    accountUnderReviewShort: "حسابك قيد المراجعة",
    pendingReviewDesc: "حسابك قيد المراجعة. يرجى التواصل مع الإدارة عبر واتساب.",
    contactAdmin: "مراسلة الإدارة عبر واتساب",
    phoneNumber: "رقم هاتفك:",
    accountVerification: "توثيق الحساب",
    verificationStatus: "الحالة:",
    verificationNotes: "ملاحظات:",
    notVerified: "غير موثق",
    pendingReview: "قيد المراجعة",
    verified: "موثق",
    rejectedVerification: "مرفوض",
    submitVerification: "إرسال طلب التوثيق",
    verificationPending: "طلب التوثيق الخاص بك قيد المراجعة.",
    verificationApproved: "تهانينا! تم توثيق حسابك.",
    submitVerificationRequest: "إرسال طلب التوثيق",
    documentType: "نوع المستند",
    documentNumber: "رقم المستند",
    documentPhoto: "صورة المستند",
    uploadDocument: "تحميل المستند",
    idCard: "بطاقة الهوية",
    passport: "جواز السفر",
    businessLicense: "رخصة التجارة",
    bookingNumber: "رقم الحجز",
    clientName: "العميل",
    message: "الرسالة",
    invoiceBtn: "الفاتورة",
    viewProfile: "الملف الشخصي",
    quickStats: "إحصائيات سريعة",
    recurringBookings: "الحجوزات الدورية",
    frequency: "التكرار",
    weekly: "أسبوعي",
    biweekly: "كل أسبوعين",
    monthly: "شهري",
    nextDate: "التاريخ التالي",
    searchPlaceholder: "بحث...",
    today: "اليوم",
    yesterday: "أمس",
    resetFilters: "إعادة ضبط الفلاتر",
    pro: "محترف",
    contactDetails: "تفاصيل الاتصال",
    enableNotificationsBtn: "تفعيل الإشعارات",
    searchConversations: "بحث في المحادثات...",
    cashInvoice: "فاتورة نقدية",
    createInvoice: "إنشاء فاتورة",
    sendInvoice: "إرسال الفاتورة",
    invoiceAmount: "المبلغ",
    invoiceNotes: "ملاحظات",
    overviewTab: "نظرة عامة",
    usersTab: "المستخدمين",
    bookingsTab: "الحجوزات",
    verificationTab: "التوثيق",
    revenueTab: "الإيرادات",
    invoicesTab: "الفواتير",
    updateSuccess: "تم التحديث",
    updateSuccessDesc: "تم تحديث المستخدم بنجاح",
    updateFailed: "خطأ",
    updateFailedDesc: "فشل تحديث المستخدم",
    verificationUpdated: "تم تحديث طلب التوثيق",
    verificationFailed: "فشل تحديث الطلب",
    totalUsersLabel: "إجمالي المستخدمين",
    providersLabel: "الحرفيون",
    totalBookingsLabel: "الحجوزات",
    verificationLabel: "طلبات التوثيق",
    revenueLabel: "الإيرادات",
    activeBookingsLabel: "الحجوزات النشطة",
    overviewLabel: "نظرة عامة",
    noUsersMessage: "لا يوجد مستخدمين بعد",
    noBookingsMessage: "لا توجد حجوزات بعد",
    usersManagementLabel: "إدارة المستخدمين",
    searchLabel: "بحث...",
    roleLabel: "الدور",
    statusLabel: "الحالة",
    allRoles: "الكل",
    clientRole: "عميل",
    providerRole: "حرفي",
    adminRole: "مدير",
    activeStatus: "نشط",
    underReviewStatus: "قيد المراجعة",
    rejectedStatus: "مرفوض",
    name: "الاسم",
    usernameLabel: "اسم المستخدم",
    emailLabel: "البريد",
    phoneLabel: "الهاتف",
    actionsLabel: "الإجراءات",
    loadingLabel: "جاري التحميل...",
    noUsersFoundMessage: "لا يوجد مستخدمين",
    adminRoleBadge: "مدير",
    providerRoleBadge: "حرفي",
    clientRoleBadge: "عميل",
    bookingManagementLabel: "إدارة الحجوزات",
    filterByStatusLabel: "تصفية حسب الحالة",
    pendingStatus: "قيد الانتظار",
    confirmedStatus: "مؤكد",
    completedStatus: "مكتمل",
    customerLabel: "العميل",
    professionalLabel: "الحرفي",
    acceptBtn: "قبول",
    rejectBtn: "رفض",
    acceptedLabel: "مقبول",
    rejectedLabel: "مرفوض",
    revenueLabel2: "الإيرادات",
    totalLabel: "الإجمالي:",
    invoicesLabel: "الفواتير",
    invoiceNumberLabel2: "فاتورة #",
    clientProviderLabel: "العميل/المزود",
    amountLabel2: "المبلغ",
    viewInvoiceBtn: "عرض الفاتورة",
    banConfirmTitle: "تأكيد الحظر",
    banConfirmDesc: "هل أنت متأكد من حظر هذا المستخدم؟",
    cancelBtn: "إلغاء",
    confirmBanBtn: "تأكيد الحظر",
    activeStatusShort: "نشط",
    confirmedStatusShort: "مؤكد",
    completedStatusShort: "مكتمل",
    cancelledStatusShort: "ملغي",
    pendingStatusShort: "قيد الانتظار",
    agreedStatusShort: "متفق عليه",
    allMarkedAsRead: "تم تحديد الكل كمقروء",
    unreadCount: "{count} غير مقروءة",
    allCaughtUp: "لا توجد غير مقروءة",
    markAllRead: "تحديد الكل",
    noNotificationsMessage: "لا توجد إشعارات",
    confirmAction: "تأكيد",
    confirmInChat: "أكّد في الشات",
    statusUpdatedMessage: "تم تحديث الحالة",
    priceLabel: "السعر",
    dateLabelShort: "التاريخ",
    contactLabel: "التواصل",
    viewAllLabel: "عرض الكل",
    messageLabel: "الرسالة",
    cancelBtnLabel: "إلغاء",
    payNowBtn: "ادفع الآن",
    invoiceBtnLabel: "الفاتورة",
    profileBtnLabel: "الملف الشخصي",
    monthlyEarnings: "أرباح الشهر",
    completedJobs: "الأشغال المكتملة",
    pendingRequests: "الطلبات المعلقة",
    averageRatingLabel: "متوسط التقييم",
    activeCitiesLabel: "المدن النشطة",
    heroBadge: "المنصة الأولى للخدمات المنزلية في المغرب",
    categories: "الفئات",
    browseServices: "تصفح الخدمات",
    browseServicesDesc: "اختر من مجموعة واسعة من الخدمات المنزلية",
    featured: "مميزون",
    whyKhidmati: "لماذا Khidmati",
    platformTrust: "منصة تثق بها",
    howItWorks: "كيف يعمل",
    threeSteps: "٣ خطوات بسيطة",
    searchAService: "ابحث عن خدمة",
    searchAServiceDesc: "اكتب الخدمة التي تحتاجها واختر مدينتك",
    chooseAPro: "اختر الحرفي",
    chooseAProDesc: "تصفح الملفات الشخصية والتقييمات واختر الأنسب",
    bookAndEnjoy: "احجز واستمتع",
    bookAndEnjoyDesc: "احجز بضغطة واحدة واستقبل الحرفي",
    forProfessionals: "للحرفيين",
    freeSetup: "إعداد مجاني خلال دقيقتين",
    boostIncome: "زيادة دخلك",
    thousandsClients: "آلاف العملاء",
    proRating: "تقييم الحرفيين",
    adminDashboard: "لوحة التحكم",
    unnamedUser: "مستخدم غير معنون",
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("khidmati-lang");
    return (saved as Language) || "ar";
  });

  useEffect(() => {
    localStorage.setItem("khidmati-lang", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      let text = TRANSLATIONS[language][key] || TRANSLATIONS["en"][key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, String(v));
        });
      }
      return text;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}
