export const MOROCCAN_CITIES = [
    "Agadir",
    "Al Hoceima",
    "Azrou",
    "Beni Mellal",
    "Berkane",
    "Berrechid",
    "Casablanca",
    "Chefchaouen",
    "Dakhla",
    "El Jadida",
    "Errachidia",
    "Essaouira",
    "Fes",
    "Guelmim",
    "Ifrane",
    "Kenitra",
    "Khemisset",
    "Khenifra",
    "Khouribga",
    "Laayoune",
    "Larache",
    "Marrakech",
    "Meknes",
    "Mohammedia",
    "Nador",
    "Ouarzazate",
    "Oujda",
    "Rabat",
    "Safi",
    "Sale",
    "Settat",
    "Sidi Kacem",
    "Sidi Slimane",
    "Tangier",
    "Taroudant",
    "Taza",
    "Temara",
    "Tetouan",
    "Tiznit"
] as const;

export const SERVICE_CATEGORIES = [
    "Plumbing",
    "Electrician",
    "Cleaning",
    "Beauty",
    "Moving",
    "Painting",
    "Carpentry",
    "Gardening",
    "Appliance Repair",
    "HVAC",
    "Pest Control",
    "Tutoring"
] as const;
